logging:
  level:
    ROOT: warn
    org.cougars: info
server.context-path: /quickAccessBookmark
spring:
  jpa.hibernate.ddl-auto: update
  main.banner-mode: off
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
# Do not touch anything above here unless you know what you are doing!
# Tampering may result in failure to run the app correctly.

# Enter the jdbc connection string, username, and password for your database here
# If running a default mysql installation on the same host as the app, no change is required to the url.
    url: jdbc:mysql://address=(protocol=tcp)(host=localhost)(port=3306)/QUICK_ACCESS_BOOKMARK?verifyServerCertificate=false&useSSL=false&requireSSL=false&createDatabaseIfNotExist=true
    username: mscougars
    password: TheProject24680!