logging.level.org.apache.http.client.protocol.ResponseProcessCookies: error
server.servlet.context-path: /
spring:
  servlet.multipart.max-file-size: 5MB
  jpa.hibernate.ddl-auto: update
  main.banner-mode: "off"
