logging:
  level:
    ROOT: info
    org.cougars: debug
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa.hibernate.ddl-auto: create-drop