logging:
  level:
    ROOT: info
    org.cougars: debug
spring:
  datasource:
    url: jdbc:mysql://address=(protocol=tcp)(host=localhost)(port=3306)/QUICK_ACCESS_BOOKMARK?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: mscougars
    password: TheProject24680!
    driver-class-name: com.mysql.jdbc.Driver
  jpa.hibernate.ddl-auto: update